# Generated by Django 6.1 on 2026-09-01 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employee', 'Salarié'), ('partner', 'Partenaire'), ('admin', 'Admin')], max_length=20),
        ),
    ]
