# Generated by Django 6.1 on 2026-09-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_employee_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopUp',
        ),
    ]
