# Generated by Django 6.1 on 2026-09-08 08:04

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def regularize_negative_balances(apps, schema_editor):
    """Abondement de régularisation pour les soldes tombés dans le découvert -150€.

    Le découvert est retiré du dispositif (retour au cahier des charges v1.0) : le
    plancher de solde redevient 0€. Les transactions étant strictement immuables
    (aucune écriture passée ne peut être modifiée ou supprimée), on ne réécrit pas
    l'historique : chaque salarié en négatif reçoit un ABONDMENT égal à la valeur
    absolue de son découvert, à la charge du Ministère, qui ramène son solde à 0€
    sans toucher aux paiements déjà enregistrés.

    Requête sur balance < 0 : rejouer cette migration sur une base déjà régularisée
    ne trouve plus personne à créditer, donc ne fait rien (idempotent).
    """
    Employee = apps.get_model('wallet', 'Employee')
    Transaction = apps.get_model('transactions', 'Transaction')

    for employee in Employee.objects.filter(balance__lt=Decimal('0.00')):
        shortfall = -employee.balance
        Transaction.objects.create(
            transaction_type='ABONDMENT',
            employee=employee,
            partner=None,
            amount=shortfall,
        )
        employee.balance = Decimal('0.00')
        employee.save(update_fields=['balance'])


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_employee_employee_balance_non_negative_and_more'),
        ('transactions', '0005_alter_transaction_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(regularize_negative_balances, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='employee',
            name='employee_balance_overdraft_limit',
        ),
        migrations.AlterField(
            model_name='employee',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'), message='Le solde ne peut pas être négatif.')]),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.CheckConstraint(condition=models.Q(('balance__gte', Decimal('0.00'))), name='employee_balance_non_negative'),
        ),
    ]
