# Generated by Django 6.1 on 2026-09-01 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
