# Generated by Django 6.1 on 2026-09-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_ministerspotlight'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ministerspotlight',
            name='single_active_ministerspotlight',
        ),
        migrations.DeleteModel(
            name='MinisterSpotlight',
        ),
    ]
