# Generated by Django 6.1 on 2026-09-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0005_remove_ministerspotlight_single_active_ministerspotlight_and_more'),
        ('partners', '0005_rename_named_partners'),
    ]

    operations = [
    ]
