# Generated by Django 6.1 on 2026-09-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='transaction',
            name='token',
            field=models.CharField(default=0, editable=False, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
