# Generated by Django 6.1 on 2026-09-07 08:58

import transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='token',
            field=models.CharField(default=transactions.models.generate_transaction_token, editable=False, max_length=100, unique=True),
        ),
    ]
